---
name: Manage Terraform state from CI/CD
on:
  push:
    branches: ["main"]

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    env:
      AWS_ENDPOINT_URL_S3: "${{ vars.S3_ENDPOINT }}"
      TERRAFORM_RC: "${{ secrets.TERRAFORM_RC }}"

      TF_VAR_auth_username: ${{ secrets.TF_VAR_AUTH_USERNAME }}
      TF_VAR_auth_password: ${{ secrets.TF_VAR_AUTH_PASSWORD }}
      TF_VAR_auth_project_id: ${{ secrets.TF_VAR_AUTH_PROJECT_ID }}
      TF_VAR_s3_access_key: ${{ secrets.S3_ACCESS_KEY }}
      TF_VAR_s3_secret_key: ${{ secrets.S3_SECRET_KEY }}
      TF_VAR_s3_bucket: ${{ vars.S3_BUCKET }}
      TF_VAR_s3_region: ${{ vars.S3_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Prepare .terraformrc
        run: echo "$TERRAFORM_RC" > ~/.terraformrc

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform apply
        run: terraform apply -auto-approve

      - name: wait for sync
        run: for i in {1..10}; do terraform refresh && break || sleep 60; done
